### ISSUE TITLE
maven update

### ISSUE THREAD

**Issue by juwitaw** [joandre/MCL_spark#12]
Hello,
I'm trying to use MCL_spark using maven from [spark-packages](https://spark-packages.org/package/joandre/MCL_spark)
When I saw, the github latest update is four months ago, but at spark-packages released date is August 2016.
I wonder will there any update for maven package?
Thank you

**Comment by joandre** [comment]
Hi,

Indeed, there will be a new update when this issue will be solved: https://github.com/joandre/MCL_spark/issues/10.

Joan

**Comment by juwitaw** [comment]
Thank you for your respond.
I'll be waiting 👍

**Comment by nishanthsiva** [comment]
Hi,

Do you have Issue #10 solved yet? We are using your MCL program as part of our system but the RAM requirements are way too high for a sparse graph with about 3 million edges. Do you have a timeline on when the next update will be pushed?

Thanks

**Comment by joandre** [comment]
Hi nishanthsiva,

Indeed. It is not solved yet. No timeline right now. I wait for a pull-request from another user. Just to let you know that it comes from Spark API that is not adapted to sparse matrix multiplication.
