### ISSUE TITLE
OOM with 200 million vertex  when matrix multiply

### ISSUE THREAD

**Issue by icesx** [joandre/MCL_spark#15]
i have 2 dataset with 200 millions vertex.i build the two dataset to tow matrix then to multiply then .but run out with oom when use this code the oom appear at blockmatrix.simulateMultiply . there is a collect action at this method. when application run there the driver will oom.
i think maybe it is a spark bug
how can i fix it

**Comment by joandre** [comment]
Hi

Indeed this could come from Spark. I saw you opened a Jira [issue](https://issues.apache.org/jira/browse/SPARK-21118) about this topic which remains the best way to move forward the project. For your information, we have an [issue](https://github.com/joandre/MCL_spark/issues/10) dedicated to calculation optimization (and particularly Sparse Matrix Multiplication in Spark). I close this one to keep all topics related to this one in the same stream.
